version: '3.8'
services:
  auth:
    build: ./cmd/auth
    ports:
      - "8080:8080"
    environment:
      - JWT_SECRET=your-secret-key
    depends_on:
      - redis
      - postgres
  listing:
    build: ./cmd/listing
    ports:
      - "8081:8081"
    environment:
      - LNBITS_API_KEY=your-lnbits-api-key
    depends_on:
      - redis
      - postgres
      - lnbits
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=marketplace
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  lnbits:
    image: lnbits/lnbits:latest
    environment:
      - LNBITS_PORT=5000
      - LNBITS_BACKEND_WALLET=your-lnd-config
    ports:
      - "5000:5000"
volumes:
  postgres-data:
